# Generated by Django 4.2.2 on 2023-12-16 04:55

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_profile_postal_code_remove_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz0123456789', length=7, max_length=25, prefix=''),
        ),
    ]
