# Generated by Django 4.2.2 on 2023-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='home', max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField(max_length=500)),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.IntegerField(max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_gallery')),
            ],
        ),
    ]
