# Generated by Django 4.2.2 on 2023-12-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_room_image1_room_image2_alter_hotel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image1',
            field=models.FileField(default='test', upload_to='hotel_gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image2',
            field=models.FileField(default='test', upload_to='hotel_gallery'),
            preserve_default=False,
        ),
    ]
