# Generated by Django 4.2.2 on 2023-12-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_remove_room_image1_remove_room_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='about', max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('position', models.TextField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('links', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='services', max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_gallery')),
            ],
        ),
    ]
