# Generated by Django 4.2.2 on 2023-12-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_managementteam_servicessection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementteam',
            old_name='links',
            new_name='Social_links',
        ),
    ]
