# Generated by Django 4.2.2 on 2023-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='carousel_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(default='test', max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image3',
            field=models.FileField(default='test', upload_to='hotel_gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image4',
            field=models.FileField(default='test', upload_to='hotel_gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
