# Generated by Django 4.2.2 on 2023-12-28 14:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_roomtype_carousel_number_roomtype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
