# Generated by Django 4.2.2 on 2023-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_alter_roomtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default='test', max_length=9000),
            preserve_default=False,
        ),
    ]
